### ISSUE TITLE
Debug print statement has not been commented out and might be a bit confusing

### ISSUE THREAD

**Issue by RenatGilmanov** [Lundez/JavaSymSpell#11]
https://github.com/Lundez/JavaSymSpell/blob/3c48d730cd28d716f777aca1aa8a349181b0e2b0/src/main/java/SymSpell/SymSpell.java#L135

@Lundez, thank you for all the hard work ;)

**Comment by Lundez** [comment]
Thanks, found a commented print too while searching. See https://github.com/Lundez/JavaSymSpell/pull/12

I'll close this as I merge the PR.

Once again, thanks!
