### ISSUE TITLE
where is SymSpell.SymSpell.SuggestionStage.Node ?

### ISSUE THREAD

**Issue by harsh-98** [Lundez/JavaSymSpell#2]
In chunkarray file SymSpell.SymSpell.SuggestionStage.Node is needed !! 
But no description is given where to find it.
Help wanted

**Comment by Lundez** [comment]
Hello!

If you watch the imports you'll find out that it's found in the SymSpell-class 
`import  SymSpell.SymSpell.SuggestionStage.Node;`
(https://github.com/Lundez/JavaSymSpell/blob/master/SymSpell.java).

I'll update the code with comments to clarify this, I'll also refactor the code to improve the imports. 

Hope this helps, please write back if it stays an issue. I'll close this issue on tuesday if you haven't answered.
//Lundez

Edit: Finished refactorization.
