### ISSUE TITLE
Completions

### ISSUE THREAD

**Issue by trans** [Lundez/JavaSymSpell#5]
I would also like to add a completions method -- return all the words that start with a given prefix. It would be cool if it could also handle spelling errors in the prefix, but one step at a time.

Would this be an acceptable pull request?

**Comment by Lundez** [comment]
Yes indeed. Just create a new method. I actually implemented this (all words given prefix) in my Master Thesis but never pushed it to SymSpell. Could look into it again.

It is easily achievable by changing the _EditDistance.java_ file.

The spell correction of prefix should be rather simple to implement as well, but creating to many "rules" or what to call it might introduce unexpected errors in my experience.

**Comment by Lundez** [comment]
I believe that this was a non-issue and self-solved locally as no response was given. Closing issue.
