### ISSUE TITLE
Update to SymSpell 6.3

### ISSUE THREAD

**Issue by loretoparisi** [Lundez/JavaSymSpell#8]
Any plan to update this release to latest SymSpell version? 
The v6.4 has [introduced](https://github.com/wolfgarbe/SymSpell#changes-in-v63) important changes most of them related to the new `WordSegmentation`. A minor change to `maxEditDistance` to speed up lookup.

Thank you.

**Comment by Lundez** [comment]
Hello Loreto!

I'll take a look at it this weekend and hopefully have it implemented by
Sunday. :)

Best regards,
Hampus (Londet)

Den sön 18 nov. 2018 18:50 skrev Loreto Parisi <notifications@github.com>:

**Comment by Lundez** [comment]
Update:
I've started to look into it, it'll be some work to actually find where to change the java-version as they're not completely identical in how code is structured. I don't think I'll be finished this sunday anymore unfortanely. But I'll try to wrap it up asap!

**Comment by loretoparisi** [comment]
@Lundez thanks for the details! 🥇

**Comment by Lundez** [comment]
Hi, I just uploaded a 'beta' version directly on top of master as the changes won't make any difference to the core-code.

The code should be "finished", but I believe there is some minor issues to pan out..

It contains both changes you wanted the most 👍

**Comment by loretoparisi** [comment]
@Lundez thank you so much to be so fast! I will merge my code in dev and try it out! Closing then.
