### ISSUE TITLE
Word Segmentation

### ISSUE THREAD

**Issue by Tyruiop** [Lundez/JavaSymSpell#9]
Hi,

I couldn't manage to access the `correctedString` and `segmentedString` fields of Word Segmentation, so I locally changed them to public fields and now it works.

Not sure if that's the correct way of doing it though?

Thanks for the port!

**Comment by Lundez** [comment]
Hi, I'll look into this sometime soon.
Sounds weird, looking at the code it seems that you're correct. I can't recall exactly how I tested it anymore.. Perhaps it was local testing within the file.

I'll get back to you but good that you managed to fix it in the meantime!

**Comment by Tyruiop** [comment]
Thank you for the reply, if it helps I can submit a merge request

**Comment by Lundez** [comment]
Let's do that! @Tyruiop
